services:
  - type: web
    name: seo-tag-extractor
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
      chmod -R +x ./browsers
    startCommand: gunicorn --workers 4 --timeout 120 --bind :10000 --pythonpath . app:app
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: ./browsers
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: NODE_VERSION
        value: 24.1.0
    plan: free