services:
  - type: web
    name: seo-tag-extractor
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium --with-deps
      find ./browsers -type f -exec chmod +x {} \;
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: ./browsers
      - key: PYTHON_VERSION
        value: 3.10
    plan: free