services:
  - type: web
    name: seo-tag-extractor
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
      chmod -R +x ./browsers
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: ./browsers
      - key: PYTHON_VERSION
        value: 3.11  # Match actual Python version in logs
    plan: free