services:
  - type: web
    name: seo-tag-extractor
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps
      find ./browsers -type d -exec chmod 755 {} \;  # Permission fix (if needed)
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: ./browsers
      - key: PYTHON_VERSION
        value: 3.10
    plan: free  